# Generated by Django 6.0.5 on 2026-05-27 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP_MM", "SAP MM Export"),
                            ("UTILITY_INTERVAL", "Utility Interval"),
                            ("TRAVEL_CONCUR", "Travel (Concur/Navan)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("file_name", models.CharField(max_length=512)),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA-256 of raw uploaded bytes. Prevents duplicate uploads.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("PARSING", "Parsing"),
                            ("NORMALIZING", "Normalizing"),
                            ("FAILED", "Failed"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="QUEUED",
                        max_length=15,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("parsed_rows", models.IntegerField(default=0)),
                ("failed_rows", models.IntegerField(default=0)),
                ("suspicious_rows", models.IntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_jobs",
                        to="core.tenant",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_job",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="RawUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "row_number",
                    models.IntegerField(
                        help_text="Original line number in source file"
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        help_text="Verbatim key-value pairs as extracted from source row"
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "immutable_hash",
                    models.CharField(
                        help_text="SHA-256 of raw_payload JSON string. Cryptographic fingerprint for tamper detection.",
                        max_length=64,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_uploads",
                        to="ingestion.ingestionjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_uploads",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "raw_upload",
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="ParsedRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "parse_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of {field, raw_value, error_type} objects",
                    ),
                ),
                (
                    "detected_schema",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "SAP_MB51_DE_LOCALE", "UTILITY_15MIN_KWH"',
                        max_length=100,
                    ),
                ),
                (
                    "locale_detected",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "de-DE", "en-US"',
                        max_length=10,
                    ),
                ),
                (
                    "date_format_inferred",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "DD.MM.YYYY", "MM/DD/YYYY"',
                        max_length=30,
                    ),
                ),
                ("parsed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsed_row_set",
                        to="ingestion.ingestionjob",
                    ),
                ),
                (
                    "raw",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsed_row",
                        to="ingestion.rawupload",
                    ),
                ),
            ],
            options={
                "db_table": "parsed_row",
            },
        ),
    ]
