# Generated by Django 6.0.5 on 2026-05-27 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirportReferenceTable",
            fields=[
                (
                    "iata_code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("airport_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                (
                    "country",
                    models.CharField(help_text="ISO 3166-1 alpha-3", max_length=3),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "is_city_code",
                    models.BooleanField(
                        default=False,
                        help_text="True for city codes (NYC, BJS) that map to multiple airports",
                    ),
                ),
            ],
            options={
                "db_table": "airport_reference_table",
            },
        ),
        migrations.CreateModel(
            name="EmissionFactorTable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "material_group",
                    models.CharField(
                        help_text="SAP MATKL or canonical activity category",
                        max_length=50,
                    ),
                ),
                (
                    "scope_category",
                    models.CharField(
                        choices=[
                            ("SCOPE_1", "Scope 1"),
                            ("SCOPE_2", "Scope 2"),
                            ("SCOPE_3", "Scope 3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("activity_type", models.CharField(max_length=100)),
                (
                    "unit",
                    models.CharField(
                        help_text='Denominator unit, e.g. "L", "kWh", "km"',
                        max_length=20,
                    ),
                ),
                (
                    "factor_value",
                    models.DecimalField(
                        decimal_places=8, help_text="kgCO2e per unit", max_digits=20
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text='e.g. "DEFRA 2024", "IEA 2024", "CEA India 2023"',
                        max_length=255,
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL for global factors",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emission_factors",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "emission_factor_table",
            },
        ),
        migrations.CreateModel(
            name="PlantMaster",
            fields=[
                (
                    "plant_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("plant_name", models.CharField(max_length=255)),
                (
                    "country",
                    models.CharField(help_text="ISO 3166-1 alpha-3", max_length=3),
                ),
                (
                    "state_province",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "grid_emission_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="kgCO2e/kWh for Scope 2",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_virtual",
                    models.BooleanField(
                        default=False, help_text="True for placeholder codes like 9999"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plants",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "plant_master",
            },
        ),
        migrations.CreateModel(
            name="UoMSynonymMap",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "internal_code",
                    models.CharField(help_text='e.g. "ST", "KL", "GAL"', max_length=10),
                ),
                (
                    "language_key",
                    models.CharField(help_text='e.g. "DE", "EN"', max_length=2),
                ),
                (
                    "iso_code",
                    models.CharField(help_text='e.g. "EA", "L", "GLL"', max_length=10),
                ),
                (
                    "dimension",
                    models.CharField(
                        help_text='"count", "volume", "mass", "energy"', max_length=20
                    ),
                ),
                (
                    "base_unit",
                    models.CharField(
                        help_text="SI base unit for this dimension", max_length=10
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=10,
                        help_text="Multiplier to convert to base unit",
                        max_digits=20,
                    ),
                ),
            ],
            options={
                "db_table": "uom_synonym_map",
                "unique_together": {("internal_code", "language_key")},
            },
        ),
    ]
