# Generated by Django 6.0.5 on 2026-05-27 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ingestion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalActivityRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP_MM", "SAP MM Export"),
                            ("UTILITY_INTERVAL", "Utility Interval"),
                            ("TRAVEL_CONCUR", "Travel (Concur/Navan)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_document_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SAP material doc number, booking locator, meter serial",
                        max_length=255,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "fuel_combustion", "grid_electricity", "air_travel"',
                        max_length=100,
                    ),
                ),
                (
                    "scope_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SCOPE_1", "Scope 1"),
                            ("SCOPE_2", "Scope 2"),
                            ("SCOPE_3", "Scope 3"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "scope_subcategory",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "stationary_combustion", "purchased_electricity"',
                        max_length=100,
                    ),
                ),
                (
                    "ghg_protocol_category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="GHG Protocol Category 1-15 for Scope 3",
                        max_length=100,
                    ),
                ),
                ("activity_date", models.DateField(blank=True, null=True)),
                ("reporting_period_year", models.IntegerField(blank=True, null=True)),
                ("reporting_period_month", models.IntegerField(blank=True, null=True)),
                (
                    "raw_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "raw_unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Exactly as it appeared in source",
                        max_length=20,
                    ),
                ),
                (
                    "raw_quantity_string",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Original string, e.g. "500.00-" or "1.500,50"',
                        max_length=50,
                    ),
                ),
                (
                    "normalized_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "normalized_unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='ISO standard unit, e.g. "L", "kWh", "km"',
                        max_length=20,
                    ),
                ),
                (
                    "unit_dimension",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='"volume", "mass", "energy", "distance"',
                        max_length=20,
                    ),
                ),
                ("emission_factor_id", models.UUIDField(blank=True, null=True)),
                (
                    "emission_factor_value",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "emission_factor_unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "kgCO2e/L"',
                        max_length=50,
                    ),
                ),
                (
                    "calculated_emissions",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="In kgCO2e",
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("emissions_locked", models.BooleanField(default=False)),
                (
                    "facility_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SAP plant code, meter account, entity name",
                        max_length=100,
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "supplier_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SAP LIFNR, vendor, airline code",
                        max_length=100,
                    ),
                ),
                (
                    "material_group",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        help_text="0.000 to 1.000, computed deterministically",
                        max_digits=4,
                    ),
                ),
                (
                    "review_priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "anomaly_flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of AnomalyFlag references",
                    ),
                ),
                (
                    "normalization_rules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered array of applied rule identifiers",
                    ),
                ),
                ("requires_human_review", models.BooleanField(default=False)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("AUDIT_LOCKED", "Audit Locked"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "immutable_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 of raw_payload at ingestion",
                        max_length=64,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("audit_locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Source-specific fields that don't generalize",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_records",
                        to="ingestion.ingestionjob",
                    ),
                ),
                (
                    "raw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_records",
                        to="ingestion.rawupload",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_records",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "canonical_activity_record",
                "ordering": ["confidence_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NormalizationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LEXICAL_CAST", "Lexical Cast"),
                            ("UOM_NORMALIZATION", "UoM Normalization"),
                            ("LEADING_ZERO_RESTORE", "Leading Zero Restore"),
                            ("LOCALE_PARSE", "Locale Parse"),
                            (
                                "MOVEMENT_TYPE_CLASSIFICATION",
                                "Movement Type Classification",
                            ),
                            (
                                "DENSITY_CONVERSION_MANUAL",
                                "Density Conversion (Manual)",
                            ),
                            ("SCOPE_ASSIGNMENT", "Scope Assignment"),
                            ("EMISSION_FACTOR_APPLIED", "Emission Factor Applied"),
                            ("MANUAL_CORRECTION", "Manual Correction"),
                            ("DUPLICATE_REMOVAL", "Duplicate Removal"),
                            ("INTERVAL_GAP_DETECTION", "Interval Gap Detection"),
                            ("AIRPORT_ENRICHMENT", "Airport Enrichment"),
                            ("DISTANCE_CALCULATION", "Distance Calculation"),
                            ("CABIN_CLASS_MULTIPLIER", "Cabin Class Multiplier"),
                            ("STATUS_FILTER", "Status Filter"),
                            ("REACTIVE_POWER_EXCLUSION", "Reactive Power Exclusion"),
                            ("ACTIVE_EXPORT_EXCLUSION", "Active Export Exclusion"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Which field was transformed", max_length=100
                    ),
                ),
                (
                    "before_value",
                    models.TextField(
                        blank=True, default="", help_text="Original value as string"
                    ),
                ),
                (
                    "after_value",
                    models.TextField(
                        blank=True, default="", help_text="Transformed value as string"
                    ),
                ),
                (
                    "rule_applied",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "trailing_minus_regex", "T006A_ST_to_EA"',
                        max_length=255,
                    ),
                ),
                (
                    "applied_by",
                    models.CharField(
                        choices=[("SYSTEM", "System"), ("ANALYST", "Analyst")],
                        default="SYSTEM",
                        max_length=10,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Required when applied_by = ANALYST",
                    ),
                ),
                (
                    "applied_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="normalization_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalization_events",
                        to="normalization.canonicalactivityrecord",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalization_events",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "normalization_event",
                "ordering": ["applied_at"],
            },
        ),
    ]
