# Generated by Django 6.0.5 on 2026-05-27 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("normalization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("MISSING_COST_CENTER", "Missing Cost Center"),
                            ("CROSS_DIMENSIONAL_UOM", "Cross-Dimensional UoM"),
                            ("LEADING_ZERO_TRUNCATION", "Leading Zero Truncation"),
                            ("TRAILING_MINUS", "Trailing Minus"),
                            ("MULTILINGUAL_HEADER", "Multilingual Header Detected"),
                            ("DUPLICATE_TIMESTAMP", "Duplicate Timestamp"),
                            ("MISSING_INTERVAL", "Missing Interval"),
                            ("UNIT_SHIFT_MWH", "Unit Shift MWh→kWh"),
                            ("ACTIVE_EXPORT_DETECTED", "Active Export Detected"),
                            ("REACTIVE_POWER_EXCLUDED", "Reactive Power Excluded"),
                            ("CANCELED_TICKET", "Canceled Ticket"),
                            ("DUPLICATE_SEGMENT", "Duplicate Segment"),
                            ("MISSING_AIRPORT_CODE", "Missing Airport Code"),
                            ("MISSING_DISTANCE", "Missing Distance"),
                            ("AMBIGUOUS_AIRPORT", "Ambiguous Airport (City Code)"),
                            ("AMBIGUOUS_TRAVEL_CATEGORY", "Ambiguous Travel Category"),
                            ("ORPHANED_MATERIAL", "Orphaned Material"),
                            ("VIRTUAL_PLANT_CODE", "Virtual Plant Code"),
                            (
                                "MISSING_SUPPLIER_ON_REVERSAL",
                                "Missing Supplier on Reversal",
                            ),
                            ("EUROPEAN_NUMBER_FORMAT", "European Number Format"),
                        ],
                        max_length=35,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("BLOCKING", "Blocking"),
                        ],
                        max_length=10,
                    ),
                ),
                ("auto_resolvable", models.BooleanField(default=False)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("AUTO_RESOLVED", "Auto-Resolved"),
                            ("ANALYST_RESOLVED", "Analyst Resolved"),
                            ("WAIVED", "Waived"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_flag_records",
                        to="normalization.canonicalactivityrecord",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_flags",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "anomaly_flag",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reporting_period",
                    models.CharField(
                        help_text='e.g. "FY2025", "FY2025-Q1"', max_length=20
                    ),
                ),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "record_count",
                    models.IntegerField(
                        help_text="How many records were locked in this batch"
                    ),
                ),
                (
                    "total_emissions",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Sum of calculated_emissions at lock time (kgCO2e)",
                        max_digits=20,
                    ),
                ),
                (
                    "lock_hash",
                    models.CharField(
                        help_text="SHA-256 of all record immutable_hashes in sorted order",
                        max_length=64,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "locked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_locks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_locks",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "audit_lock",
                "ordering": ["-locked_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CLAIM", "Claim"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("REQUEST_MORE_INFO", "Request More Info"),
                            ("EDIT_AND_APPROVE", "Edit and Approve"),
                            ("ESCALATE", "Escalate"),
                            ("WAIVE_FLAG", "Waive Flag"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("AUDIT_LOCKED", "Audit Locked"),
                        ],
                        max_length=15,
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Mandatory for REJECT, EDIT_AND_APPROVE, WAIVE_FLAG",
                    ),
                ),
                (
                    "fields_edited",
                    models.JSONField(
                        blank=True,
                        help_text="For EDIT_AND_APPROVE: which fields were changed and why",
                        null=True,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_events",
                        to="normalization.canonicalactivityrecord",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_events",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "review_event",
                "ordering": ["performed_at"],
            },
        ),
    ]
